### ISSUE TITLE
Problem with generated URL

### ISSUE THREAD

**Issue by drawcard** [stephanediondev/readerself-feeder-for-chrome#1]
Hi, whenever I click the icon in the URL bar to add a feed, and then select the feed, the generated URL is invalid - it seems to insert the Chrome extension URL before the hosted Reader Self installation location:

```
chrome-extension://lnjjeiphdakecehcmeincfglpaabdiaf/rss.xxxxxxxxxx.com.au/?u=http://jquer.in/feed/
```

This then generates a 404 not found error.

I then have to manually edit this to remove the "Chrome-extension" reference, like so:

```
rss.xxxxxxxxxx.com.au/?u=http://jquer.in/feed/
```

then the feed is added properly.

**Comment by stephanediondev** [comment]
Hi

Did you set your url with http:// or https:// ?

![image](https://cloud.githubusercontent.com/assets/528192/12941668/f155d0f2-cfd4-11e5-968c-dde3bd1aaddd.png)
